# Pipeline de Deploy - BI São Luís
image: python:3.9

pages:
  stage: deploy
  script:
    - pip install streamlit pandas plotly pyarrow openpyxl
    - mkdir public
    # Este comando cria o ponto de entrada para o GitLab reconhecer o site
    - cp dashboard_mestre_sao_luis_v34_final.py public/
    # Criamos um arquivo simples de redirecionamento para o Streamlit Cloud ou Stlite
    - echo "Redirecionando para o Dashboard..." > public/index.html
  artifacts:
    paths:
      - public
  only:
    - main